# Data Loading

### 1. Reading a file

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("/home/user/DSP_Lab/Airline_Project/CSV_files/test.csv")
df.shape

(25976, 25)

### 2. Checking Datatypes

In [2]:
df.info

<bound method DataFrame.info of        Unnamed: 0     id  Gender      Customer Type  Age   Type of Travel  \
0               0  19556  Female     Loyal Customer   52  Business travel
1               1  90035  Female     Loyal Customer   36  Business travel
2               2  12360    Male  disloyal Customer   20  Business travel
3               3  77959    Male     Loyal Customer   44  Business travel
4               4  36875  Female     Loyal Customer   49  Business travel
...           ...    ...     ...                ...  ...              ...
25971       25971  78463    Male  disloyal Customer   34  Business travel
25972       25972  71167    Male     Loyal Customer   23  Business travel
25973       25973  37675  Female     Loyal Customer   17  Personal Travel
25974       25974  90086    Male     Loyal Customer   14  Business travel
25975       25975  34799  Female     Loyal Customer   42  Personal Travel

          Class  Flight Distance  Inflight wifi service  \
0           Eco              160                      5
1      Business             2863                      1
2           Eco              192                      2
3      Business             3377                      0
4           Eco             1182                      2
...         ...              ...                    ...
25971  Business              526                      3
25972  Business              646                      4
25973       Eco              828                      2
25974  Business             1127                      3
25975       Eco              264                      2

       Departure/Arrival time convenient  ...  Inflight entertainment  \
0                                      4  ...                       5
1                                      1  ...                       4
2                                      0  ...                       2
3                                      0  ...                       1
4                                      3  ...                       2
...                                  ...  ...                     ...
25971                                  3  ...                       4
25972                                  4  ...                       4
25973                                  5  ...                       2
25974                                  3  ...                       4
25975                                  5  ...                       1

       On-board service  Leg room service  Baggage handling  Checkin service  \
0                     5                 5                 5                2
1                     4                 4                 4                3
2                     4                 1                 3                2
3                     1                 1                 1                3
4                     2                 2                 2                4
...                 ...               ...               ...              ...
25971                 3                 2                 4                4
25972                 4                 5                 5                5
25973                 4                 3                 4                5
25974                 3                 2                 5                4
25975                 1                 2                 1                1

       Inflight service  Cleanliness  Departure Delay in Minutes  \
0                     5            5                          50
1                     4            5                           0
2                     2            2                           0
3                     1            4                           0
4                     2            4                           0
...                 ...          ...                         ...
25971                 5            4                           0
25972                 5            4                           0
25973                 4            2                           0
25974                 5            4                           0
25975                 1            1                           0

       Arrival Delay in Minutes             Satisfaction
0                          44.0                satisfied
1                           0.0                satisfied
2                           0.0  neutral or dissatisfied
3                           6.0                satisfied
4                          20.0                satisfied
...                         ...                      ...
25971                       0.0  neutral or dissatisfied
25972                       0.0                satisfied
25973                       0.0  neutral or dissatisfied
25974                       0.0                satisfied
25975                       0.0  neutral or dissatisfied

[25976 rows x 25 columns]>

### 3. Checking columns

In [3]:
df.columns

Index(['Unnamed: 0', 'id', 'Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'Satisfaction'],
      dtype='object')

### 4. Naming unnamed columns

In [4]:
df.rename(columns={"Unnamed: 0":"Record_id"}, inplace=True)
df.columns

Index(['Record_id', 'id', 'Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'Satisfaction'],
      dtype='object')

### 5. Correcting row values of Record_id

In [5]:
df["Record_id"]=df["Record_id"]+1
df.head()

,Record_id,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Satisfaction
0,1,19556,Female,Loyal Customer,52,Business travel,Eco,160,5,4,...,5,5,5,5,2,5,5,50,44.0,satisfied
1,2,90035,Female,Loyal Customer,36,Business travel,Business,2863,1,1,...,4,4,4,4,3,4,5,0,0.0,satisfied
2,3,12360,Male,disloyal Customer,20,Business travel,Eco,192,2,0,...,2,4,1,3,2,2,2,0,0.0,neutral or dissatisfied
3,4,77959,Male,Loyal Customer,44,Business travel,Business,3377,0,0,...,1,1,1,1,3,1,4,0,6.0,satisfied
4,5,36875,Female,Loyal Customer,49,Business travel,Eco,1182,2,3,...,2,2,2,2,4,2,4,0,20.0,satisfied

# Data cleaning

### 1. Handling missing values

In [6]:
df.isnull().sum()

Record_id                             0
id                                    0
Gender                                0
Customer Type                         0
Age                                   0
Type of Travel                        0
Class                                 0
Flight Distance                       0
Inflight wifi service                 0
Departure/Arrival time convenient     0
Ease of Online booking                0
Gate location                         0
Food and drink                        0
Online boarding                       0
Seat comfort                          0
Inflight entertainment                0
On-board service                      0
Leg room service                      0
Baggage handling                      0
Checkin service                       0
Inflight service                      0
Cleanliness                           0
Departure Delay in Minutes            0
Arrival Delay in Minutes             83
Satisfaction                          0
dtype: int64

### 2. Checking the Null value rows

In [7]:
df[df["Arrival Delay in Minutes"].isnull()]

,Record_id,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Satisfaction
516,517,107365,Female,Loyal Customer,21,Personal Travel,Eco,632,1,5,...,2,4,2,5,4,5,2,9,NaN,neutral or dissatisfied
656,657,108648,Male,Loyal Customer,9,Personal Travel,Eco,762,2,5,...,4,2,5,2,5,2,4,51,NaN,neutral or dissatisfied
1071,1072,16797,Male,disloyal Customer,25,Business travel,Eco,1017,3,4,...,5,2,5,2,3,2,5,126,NaN,neutral or dissatisfied
1224,1225,30090,Male,Loyal Customer,7,Personal Travel,Eco,399,4,5,...,4,4,3,1,1,4,4,0,NaN,neutral or dissatisfied
1589,1590,41924,Female,Loyal Customer,58,Business travel,Eco,129,5,3,...,5,5,5,5,3,5,5,3,NaN,satisfied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24072,24073,21780,Male,Loyal Customer,45,Business travel,Eco,352,5,1,...,5,1,1,1,3,2,5,26,NaN,satisfied
24133,24134,64934,Female,Loyal Customer,29,Business travel,Business,3873,3,3,...,3,3,4,4,4,3,3,19,NaN,neutral or dissatisfied
24301,24302,125688,Male,disloyal Customer,38,Business travel,Business,759,3,3,...,4,3,3,5,5,4,4,0,NaN,satisfied
25128,25129,64706,Female,Loyal Customer,52,Business travel,Business,3659,5,5,...,5,5,5,5,3,5,3,0,NaN,satisfied
25468,25469,85927,Male,disloyal Customer,26,Business travel,Business,447,1,0,...,4,5,4,4,4,5,4,4,NaN,neutral or dissatisfied

In [8]:
df["Arrival Delay in Minutes"]=(df['Arrival Delay in Minutes'].astype(str).str.strip())
df["Arrival Delay in Minutes"]=pd.to_numeric(df["Arrival Delay in Minutes"], errors="coerce")
df.isnull().sum()

Record_id                             0
id                                    0
Gender                                0
Customer Type                         0
Age                                   0
Type of Travel                        0
Class                                 0
Flight Distance                       0
Inflight wifi service                 0
Departure/Arrival time convenient     0
Ease of Online booking                0
Gate location                         0
Food and drink                        0
Online boarding                       0
Seat comfort                          0
Inflight entertainment                0
On-board service                      0
Leg room service                      0
Baggage handling                      0
Checkin service                       0
Inflight service                      0
Cleanliness                           0
Departure Delay in Minutes            0
Arrival Delay in Minutes             83
Satisfaction                          0
dtype: int64

> We removed hidden/extra whitespace from the column and standardized it to numeric. After this step, 83 values were still truly missing, so we handled them separately.

In [9]:
df["Arrival Delay in Minutes"]=df["Arrival Delay in Minutes"].fillna(df["Arrival Delay in Minutes"].median())
df.isnull().sum()

Record_id                            0
id                                   0
Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
Satisfaction                         0
dtype: int64

> We used Median Imputation, beacause it prevents distortion in Model Prediction.
After this step There are no Missing Values in this step.

# Data Formatting

### 1. Converting Target column to Numbers

In [10]:
df["Satisfaction"] = (
    df["Satisfaction"].astype(str)
    .str.strip()
    .str.lower()
)

In [11]:
df["Satisfaction"] = df["Satisfaction"].map({
    "satisfied": 1,
    "neutral or dissatisfied": 0
})

In [12]:
display(df)

,Record_id,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Satisfaction
0,1,19556,Female,Loyal Customer,52,Business travel,Eco,160,5,4,...,5,5,5,5,2,5,5,50,44.0,1
1,2,90035,Female,Loyal Customer,36,Business travel,Business,2863,1,1,...,4,4,4,4,3,4,5,0,0.0,1
2,3,12360,Male,disloyal Customer,20,Business travel,Eco,192,2,0,...,2,4,1,3,2,2,2,0,0.0,0
3,4,77959,Male,Loyal Customer,44,Business travel,Business,3377,0,0,...,1,1,1,1,3,1,4,0,6.0,1
4,5,36875,Female,Loyal Customer,49,Business travel,Eco,1182,2,3,...,2,2,2,2,4,2,4,0,20.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25971,25972,78463,Male,disloyal Customer,34,Business travel,Business,526,3,3,...,4,3,2,4,4,5,4,0,0.0,0
25972,25973,71167,Male,Loyal Customer,23,Business travel,Business,646,4,4,...,4,4,5,5,5,5,4,0,0.0,1
25973,25974,37675,Female,Loyal Customer,17,Personal Travel,Eco,828,2,5,...,2,4,3,4,5,4,2,0,0.0,0
25974,25975,90086,Male,Loyal Customer,14,Business travel,Business,1127,3,3,...,4,3,2,5,4,5,4,0,0.0,1
25975,25976,34799,Female,Loyal Customer,42,Personal Travel,Eco,264,2,5,...,1,1,2,1,1,1,1,0,0.0,0

### 2. Removing the duplicate rows

In [13]:
df.drop_duplicates(inplace=True)

# Binning

> Binning is applied to the Age column to categorize ages into different groups.

In [14]:
df["Age_group"]=pd.cut(df["Age"], bins=[0,18, 30, 45, 60, 100],
                        labels=["Teen", "Young", "Mid", "Senior", "Old" ])

In [15]:
df.insert(df.columns.get_loc("Age")+1, "Age_group", df.pop("Age_group"))

# Descriptive Statistics

### 1. Summarizing the DataFrame

In [16]:
df.describe()

,Record_id,id,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Satisfaction
count,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,...,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.000000,25976.00000,25976.000000,25976.000000
mean,12988.500000,65005.657992,39.620958,1193.788459,2.724746,3.046812,2.756775,2.977094,3.215353,3.261665,...,3.357753,3.385664,3.350169,3.633238,3.314175,3.649253,3.286226,14.30609,14.693756,0.438982
std,7498.769632,37611.526647,15.135685,998.683999,1.335384,1.533371,1.412951,1.282133,1.331506,1.355536,...,1.338299,1.282088,1.318862,1.176525,1.269332,1.180681,1.319330,37.42316,37.466787,0.496272
min,1.000000,17.000000,7.000000,31.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,6494.750000,32170.500000,27.000000,414.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000,2.000000,0.00000,0.000000,0.000000
50%,12988.500000,65319.500000,40.000000,849.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,...,4.000000,4.000000,4.000000,4.000000,3.000000,4.000000,3.000000,0.00000,0.000000,0.000000
75%,19482.250000,97584.250000,51.000000,1744.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,...,4.000000,4.000000,4.000000,5.000000,4.000000,5.000000,4.000000,12.00000,13.000000,1.000000
max,25976.000000,129877.000000,85.000000,4983.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,1128.00000,1115.000000,1.000000

# Grouping + ANOVA

> Grouping is performed to divide the data into different categories based on travel class which helps in comparing customer satisfaction level across different groups.

In [17]:
df["Class"].unique()

array(['Eco', 'Business', 'Eco Plus'], dtype=object)

In [18]:
import scipy.stats as stats
group1=df[df["Class"]=="Business"]["Satisfaction"]
group2=df[df["Class"]=="Eco"]["Satisfaction"]
group3=df[df["Class"]=="Eco Plus"]["Satisfaction"]
print(stats.f_oneway(group1, group2, group3))

F_onewayResult(statistic=np.float64(4276.584398297498), pvalue=np.float64(0.0))

# Correlation

> Correlation analysis is performed to calculate the relationship between numerical features and the target variable Satisfaction by computing correlation values.

In [19]:
corr_matrix=df.select_dtypes(include=np.number).corr()
corr_matrix["Satisfaction"].sort_values(ascending=False)

Satisfaction                         1.000000
Online boarding                      0.494526
Inflight entertainment               0.398951
Seat comfort                         0.346275
On-board service                     0.321491
Cleanliness                          0.314350
Leg room service                     0.309629
Flight Distance                      0.295292
Inflight wifi service                0.280395
Baggage handling                     0.252415
Inflight service                     0.245573
Checkin service                      0.241495
Food and drink                       0.216868
Ease of Online booking               0.157709
Age                                  0.121697
id                                   0.010965
Record_id                            0.001511
Gate location                       -0.016627
Departure Delay in Minutes          -0.051635
Arrival Delay in Minutes            -0.060993
Departure/Arrival time convenient   -0.064798
Name: Satisfaction, dtype: float64

In [20]:
df.to_csv("/home/user/DSP_Lab/Airline_Project/CSV_files/data_preprocessing.csv", index=False)